[package]
name = "influxdb"
version = "0.1.0"
authors = ["Gero Gerke <11deutron11@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.17"
futures = "0.1.27"
tokio = "0.1.20"
itertools = "0.8"
failure = "0.1.5"
serde = { version = "1.0.92", optional = true }
serde_json = { version = "1.0", optional = true }

[features]
serde-orm = ["serde", "serde_json"]

default = ["serde-orm"]
